# Generated by Django 2.2.2 on 2019-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='first name', max_length=20)),
                ('mname', models.CharField(default='middle name', max_length=20)),
                ('lname', models.CharField(default='last name', max_length=20)),
                ('uname', models.CharField(default='user name', max_length=20, unique=True)),
                ('pwd', models.CharField(default='sksjdkn', max_length=30)),
                ('address', models.CharField(default='street number', max_length=50)),
                ('city', models.CharField(default='AZ', max_length=20)),
                ('state', models.CharField(default='USA', max_length=20)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
    ]
