# Generated by Django 2.2.2 on 2019-07-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.CharField(default='85281', max_length=5),
        ),
    ]
