# Generated by Django 2.2.2 on 2019-07-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinit', '0002_auto_20190707_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='Tempe', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='AZ', max_length=20),
        ),
    ]
