# Generated by Django 2.2.2 on 2019-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinit', '0003_auto_20190707_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(default='Organization name', max_length=30)),
                ('desc', models.CharField(default='Description', max_length=30)),
                ('address', models.CharField(default='address', max_length=30)),
                ('city', models.CharField(default='city', max_length=20)),
                ('zipcode', models.CharField(default='zipcode', max_length=5)),
                ('phone', models.CharField(default='phone number', max_length=10)),
                ('state', models.CharField(default='state', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mname',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
