# Generated by Django 2.2.2 on 2019-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinit', '0004_auto_20190722_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmem',
            name='upload',
            field=models.FileField(default='empty', upload_to='uploads/'),
        ),
    ]
